site_name: Technology Documentation
site_author: Alexander Lindholm
site_url: https://docs.alexanderlindholm.net
repo_url: https://github.com/Alex0424/docs

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

nav:
  - INFO: index.md

  - Linux:
    - INFO: linux/index.md
    - GUI:
      - GUI: linux/GUI/GUI.md
      - Hyprland: linux/GUI/hyprland.md
    - Text Processing:
      - AWK: linux/text_processing/awk.md
      - Cut: linux/text_processing/cut.md
      - JQ: linux/text_processing/jq.md
      - Regex: linux/text_processing/regex.md
      - SED: linux/text_processing/sed.md
    - System Monitoring:
      - Processes: linux/system_monitoring/processes.md
      - I/O: linux/system_monitoring/I-O.md
      - Disk Space: linux/system_monitoring/disk_space.md
      - Firewall: linux/system_monitoring/firewall.md
      - Load Average: linux/system_monitoring/load_average.md
      - RAM: linux/system_monitoring/ram.md
    - Bash Scripting: linux/bash_scripting.md
    - Math: linux/math.md
    - Archive: linux/archive.md
    - Commands: linux/commands.md
    - Time: linux/time.md
    - HTTP CRUD: linux/HTTP_CRUD.md
    - Env Var: linux/env_var.md
    - Filter: linux/filter.md
    - Path: linux/path.md
    - Permission: linux/permission.md
    - File System: linux/file_system.md
    - Services: linux/services.md
    - User: linux/user.md
    - Vim: linux/vim.md
    - ls: linux/ls.md
    - Hard VS Soft Link: linux/soft_link_vs_hard_link.md
    - Distros: linux/distros.md
    - Boot: linux/boot.md
    - Kernel: linux/kernel.md
    - Storage:
      - Disk Imaging:
        - Write ISO to USB: linux/storage/disk-imaging/write-iso-to-usb.md

  - Git:
    - INFO: git/index.md
    - Clone:
      - HTTP: git/clone/http.md
      - SSH: git/clone/ssh.md
      - Swap HTTP <-> SSH: git/clone/swap_http_ssh.md
    - Commands:
      - Bisect: git/commands/bisect.md
      - Branch: git/commands/branch.md
      - Checkout: git/commands/checkout.md
      - Default Commands: git/commands/default_commands.md
      - Diff: git/commands/diff.md
      - Log: git/commands/log.md
      - Status ui: git/commands/status_ui.md
      - Remote Repository: git/commands/remote_repository.md
      - Stash: git/commands/stash.md
    - Concepts:
      - Git config: git/concepts/git-config.md
      - Patchset: git/concepts/patchset.md
      - Checkout vs Cherrypick: git/concepts/checkout_vs_cherrypick.md
      - Merge vs Rebase: git/concepts/merge_vs_rebase.md

  - CI-CD:
    - INFO: CI-CD/index.md
    - Jenkins:
      - Features: CI-CD/jenkins/features.md
      - Jenkins CLI: CI-CD/jenkins/Jenkins_CLI.md
      - Job DSL: CI-CD/jenkins/Job_DSL.md
      - Pipeline Demo: CI-CD/jenkins/pipeline_demo.md
      - Plugins: CI-CD/jenkins/plugins.md
      - Slave Node: CI-CD/jenkins/slave_node.md
    - Argo:
      - Argo CD: CI-CD/Argo/argo_cd.md
      - Argo Events: CI-CD/Argo/argo_events.md
      - Argo Workflow: CI-CD/Argo/argo_workflow.md
  
  - Containerization:
    - Docker:
      - Image: containerization/docker/image.md
      - Container: containerization/docker/container.md
      - Dockerfile: containerization/docker/docker_file.md

  - AI:
    - INFO: ai/index.md
    - Fundamentals:
      - Agents: ai/fundamentals/agents.md
      - AI Models: ai/fundamentals/ai_models.md
      - Neural Networks: ai/fundamentals/neural_networks.md
      - Deep Learning: ai/fundamentals/deep_learning.md
      - General AI: ai/fundamentals/general_ai.md
      - Generative AI: ai/fundamentals/generative_ai.md
      - Hallucinations: ai/fundamentals/hallucinations.md
      - Machine Learning: ai/fundamentals/machine_learning.md
      - Machine Learning Types: ai/fundamentals/machine_learning_types.md
      - Narrow AI: ai/fundamentals/narrow_ai.md
      - Prompt: ai/fundamentals/prompt.md
      - RAG: ai/fundamentals/rag.md
      - Super AI: ai/fundamentals/super_ai.md
    - Coding with AI:
      - CLI: ai/coding_with_ai/cli.md
      - Process Flow: ai/coding_with_ai/process_flow.md

  - Agile:
    - INFO: agile/index.md

  - Kubernetes:
    - INFO: kubernetes/index.md
    - Getting Started:
        - History: kubernetes/history.md
        - Introduction: kubernetes/introduction.md
    - Setup:
        - Setup Kubectl: kubernetes/setup_kubectl.md
        - Setup Minikube: kubernetes/setup_minikube.md
        - Setup Kops: kubernetes/setup_kops.md
    - Concepts:
        - Kubernetes architecture diagram: kubernetes/kubernetes_infrastructure_diagram.md
        - Commands & Arguments: kubernetes/commands_arguments.md
        - Objects: kubernetes/objects.md
        - Namespace: kubernetes/namespaces.md
        - Kube Config: kubernetes/kube_config.md
        - Jobs and Cron Jobs: kubernetes/jobs_cron_jobs.md
        - DaemonSet: kubernetes/daemonset.md
        - Taints and Tolerations: kubernetes/taints_tolerations.md
        - Limits: kubernetes/limits.md
    - Workloads:
        - ReplicaSet: kubernetes/replicaset.md
        - Deployment: kubernetes/deployment.md
        - Service: kubernetes/service.md
        - Volume: kubernetes/volumes.md
        - Config Map: kubernetes/config_map.md
        - Secrets: kubernetes/secrets.md
        - ingress: kubernetes/ingress.md
    - Helm:
        - Introduction: kubernetes/helm_introduction.md
        - Hands On: kubernetes/helm_hands_on.md
        - Helm with AI: kubernetes/helm_with_ai.md
    - EKS: kubernetes/eks_introduction.md
    - Logging:
        - Different Logging: kubernetes/different_logging.md
        - Lens: kubernetes/lens.md
    - Cheat Sheet: kubernetes/cheatsheet.md

  - Cybersecurity:
    - INFO: cybersecurity/index.md
    - Threat Landscape: cybersecurity/threat-landscape.md

  - IDE:
    - INFO: IDE/index.md
    - VS Code: IDE/vscode.md

  - Computer Science:
    - Data Representation:
        - Number Bases: computer_science/data_representation/number_bases.md
        - Signed Integer Formats: computer_science/data_representation/signed_integer_formats.md
        - BCD: computer_science/data_representation/BCD.md

  - Systems Integration:
    - Middleware:
        - INFO: systems_integration/middleware/index.md
        - Message Broker:
            - Rabbit MQ: systems_integration/middleware/message_broker/rabbit_mq.md

  - Networking:
    - INFO: networking/index.md
    - OSI: networking/OSI.md
    - IP: networking/ip.md
    - Linux Commands: networking/linux_commands.md
    - HTTPS/TLS: networking/https.md

  - Windows:
    - Audit: windows/audit.md
    - Variables: windows/variables.md
    - Archive: windows/archive.md
    - Get Command: windows/get_command.md

  - Cloud Computing:
    - INFO: ./cloud_computing/index.md
    - Deployment Models: ./cloud_computing/deployment_models.md
    - Service Models: ./cloud_computing/service_models.md
  
  - Cloud:
    - INFO: cloud/index.md
    - AWS:
      - INFO: cloud/aws/index.md
      - CLI Commands: cloud/aws/cli_commands.md
      - CLI Setup: cloud/aws/CLI_Setup.md
      - CloudWatch: cloud/aws/CloudWatch.md
      - EC2: cloud/aws/EC2.md
      - SSH Setup: cloud/aws/SSH_setup.md
    - Azure:
      - INFO: cloud/azure/index.md
      - Create VM: cloud/azure/create_vm.md
      - Logs: cloud/azure/logs.md
    - GCP:
      - INFO: cloud/gcp/index.md
      - VM: cloud/gcp/vm.md

  - IAC:
    - INFO: IAC/index.md

  - Monitoring:
    - INFO: monitoring/index.md

  - Backend:
    - INFO: backend/index.md

  - Frontend:
    - INFO: frontend/index.md
